### ISSUE TITLE
Packing Queue

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#1]
- [x] "Make Packing Slip" button disabled unless a line item is selected
- [x] Line items from different "Orders" should not be able to go in the same packing slip. (If you first select a line from ABC1002, then only other lines from ABC1002 should be selectable)
- [x] Queue Number (~left~right of "Queue") should show number of line items currently in the queue.
- [x] "Fulfilled Qty" tooltip - "This includes number of items that have been packed as well as number of items that have shipped."
- [x] "Show Unfinished Batches" = true -> GET `/workOrders`
- [x] "Show Unfinished Batches" = false -> GET `/workOrders/packingQueue`
- [x] "Search" should filter displayed items by any of "Order #" or "Part"

**Comment by joshplumley** [comment]
@jarrilla Is the `Fulfilled Qty` the same as the `packedQty` that is part of the object returned from `GET workOrders/packingQueue` 
![Screenshot from 2022-01-04 19-28-39](https://user-images.githubusercontent.com/8578990/148141962-bddb5812-17b9-43e5-8e1b-7715559234c9.png)

**Comment by jarrilla** [comment]
@joshplumley  It looks like I didn't finish that aggregate accurately. For now, you can assume that, but fulfilled qty should be equal to shipped + packed.

See #14

**Comment by joshplumley** [comment]
@jarrilla its mentioned that the number should go to the left of the "QUEUE". The mock up has it to the right. Which do you prefer?
![Screenshot from 2022-01-05 12-43-38](https://user-images.githubusercontent.com/8578990/148264012-8dfcff72-6509-4d38-9006-9637e1de963a.png)

**Comment by jarrilla** [comment]
> @jarrilla its mentioned that the number should go to the left of the "QUEUE". The mock up has it to the right. Which do you prefer?
>  
Good catch. Fixed typo in the issue writeup.
Right side is preferred.

**Comment by joshplumley** [comment]
@jarrilla Similarly the mockup has "Show Unfinished" check box but the issue has "Show Unfinished Batches". Which do you prefer?

**Comment by jarrilla** [comment]
> @jarrilla Similarly the mockup has "Show Unfinished" check box but the issue has "Show Unfinished Batches". Which do you prefer?

Batches
