### ISSUE TITLE
BE: Add endpoint to do deep search of shipments

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#11]
Should be able to search by Customer Tag, or parts in a shipment manifest.
Should be a simple mongo aggregate that populates the manifest array & looks for matching strings.

Result should be paginated

Paylload for `POST /shipments/search`
```
{
  sortBy?: String // "ORDER" | "DATE"; default will be DATE
  sortOrder?: Number // -1 or +1; default will be +1
  matchOrder?: String // optional but one of (matchOrder or matchPart) is required
  matchPart?: String // optional but one of (matchOrder or matchPart) is required
  resultsPerPage: Number // required
  pageNumber?: Number // default will be 1
}
```

Needs a slight re-design of FE so we can have a clean faceted search. (See #23)

There are 2 possible pipelines depending on payload.
If `matchPart !== undefined`
```
(1) $lookup // populate manifest
(2) $match // by order & by $elemMatch parts in manifest
(3) $sort
(4) $facet // metadata: [ total, page ] & data: $skip, $limit
```

If `matchPart === undefined`
```
(1) $match // by order
(2) $lookup // populate manifest
(3) $sort
(4) $facet
```

**Comment by joshplumley** [comment]
@jarrilla Do you have a more complete postman collection that has an example for a `PUT /shipments` ?

**Comment by jarrilla** [comment]
I'll upload it after reviewing pending PRs, but the payload should be of this format:
```
{
    "customer": "_id of customer",
    "manifest": [
        "_id of packing slip to indlue",
        "another _id"
    ],
    "trackingNumber": "123456",
    "cost": 15.45 // in dollars
}
```
