### ISSUE TITLE
Refreshing tab/page resets sort directions

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#122]
I think this is one of those things that we had already fixed and sloppy merging brought it back.
Hopefully this is the last case of this that we see; sorry!

**Comment by joshplumley** [comment]
I believe this is fixed in https://github.com/conturo-prototyping/pack-ship-demo/pull/110. I don't think we ever implemented the sorting to be persisted across refreshes. Is this something you'd like?
