### ISSUE TITLE
Search Input loses focus if table item is selected

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#17]
At least in Packing Queue.. (may be an issue in future components), If a line-item is selected and we select "Search" input, the input will immediately lose focus and we have to click it again afterwards to actually use it.

**Comment by jbolles94** [comment]
@jarrilla Are you still seeing this issue? It may have gotten fixed with another pr.

**Comment by jarrilla** [comment]
Still an issue as of 8aee2fe88b0dcf37bef25ff56627d77f626e90a4

To replicate:
1. Select any line item
2. Click Search input
