### ISSUE TITLE
Packing Queue Search; sticky selected items through search filter

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#18]
If line-items are selected, they should be shown through a filter..
something like `array.filter(x.selected || new Regexp(...))` should do

**Comment by joshplumley** [comment]
So if a user has selected items you would like those items to persist on the table, regardless of meeting the search criteria?

**Comment by jarrilla** [comment]
Correct

**Comment by joshplumley** [comment]
closed by #34

**Comment by jarrilla** [comment]
@joshplumley I've just noticed that if you select a line and change the column filters such that said line is filtered out, it will not remain stuck to page.

**Comment by joshplumley** [comment]
Hmmm. OK Ill take look!
