### ISSUE TITLE
Separate 'Search' function in Shipping History

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#23]
- [x] Current "Search" input becomes split inputs
  * Order
  * Part
- [x] Add "Search" button (top right of page)
  * Endpoint: `POST /shipments/search` (see #11)
  * Button is disabled unless "order" input or "part" input are different than last search parameters.
  * _E.g.: if we last search for `Order='ABC1001'`, then any change to Order or Part inputs should re-enable the button_
- [x] Button click payload is always `pageNumber=1` (can be left out; server will default to 1)
- [x] For page 2+, the query should be called from "next page" button (bottom right of table)

![image](https://user-images.githubusercontent.com/1864792/148999167-ef95f768-bffd-4aef-ae7d-151bb6fe1192.png)

**Comment by joshplumley** [comment]
@jarrilla I should have read the later issues first, but I think I addressed all this in #28. Is that correct?

**Comment by jarrilla** [comment]
Correct.
