### ISSUE TITLE
Packing History

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#4]
- [ ] Clicking on any line should bring up a context menu with options: [ View, Download, Edit, Delete ]
- [ ] View -> Almost same as "Create Packing Slip" but "Pack Qty" is not editable & no "Cancel", "OK" buttons.
- [ ] Edit -> #5 
- [ ] Download -> Download PDF (@jarrilla )
- [ ] Delete -> Double confirm using "Do you want to delete this?" modal & hit DELETE `/packingSlips/{{ packing slip _id }}

**Comment by joshplumley** [comment]
Do you have an updated mockup of this view. It looks like https://xd.adobe.com/view/c82fade8-9d8d-40ce-8050-bbb9136c3179-9d7c/screen/5d2dab48-7f1a-4e60-b655-eb7ce21dda99/  (4/16) doesn't have the buttons located on the page yet.

**Comment by jarrilla** [comment]
What buttons are you referring to?
The idea here is to have a context menu with those options come up on click.
I can draw up a mock-up of that if necessary.

**Comment by joshplumley** [comment]
I was just wondering where the context menu should appear. Are you OK with an kebab menu in the very last column? When you click it the context menu appears?

**Comment by jarrilla** [comment]
Yes, that's fine.
