### ISSUE TITLE
Shipment Queue not refreshed properly after Shipment created

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#50]
Grid is populated with message "An error occurred."

Console is presenting this error (and a bunch of others)
![image](https://user-images.githubusercontent.com/1864792/150803884-caa4e0f0-5651-4c92-9e9d-759cccb76794.png)

**Comment by joshplumley** [comment]
@jarrilla there are quite a few of these types of things that we will for sure clean up.

**Comment by joshplumley** [comment]
this is fixed in #54
