### ISSUE TITLE
Shipping Queue

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#6]
- [ ] "Create Shipment" button is disabled until at least one line item is selected
- [ ] Lines from different customers cannot be selected; same customer w/ different order # is ok. (E.g. ABC1001 & ABC1002 OK; ABC1001 & BCD1001 NOT OK).
- [ ] Clicking anywhere on the line should toggle its contents. (Something like a treelist view -- contents can span row)
- [ ] Add a part description below each part's # & qty
- [ ] "Search" should filter by Order #, or contents of packing slip. (E.g. if packing slip ABC1001 has part "HELLO" then searching for "hello" should show ABC1001; no need to also trim packing slip contents)

**Comment by jbolles94** [comment]
@jarrilla It looks like the endpoint `localhost:3000/shipments/queue` is missing the Due Date data for the shipping queue. Do we need an issue to add that data to the queue or am I missing a piece of it?

**Comment by jbolles94** [comment]
@jarrilla On another note, it looks like the same endpoint is missing the customerID. Should that be included? Or do I need to call something else to get it?

**Comment by jbolles94** [comment]
@jarrilla For the task stating `Add a part description below each part's # & qty`, where does the part description come from and where on the table should it be placed?

**Comment by jbolles94** [comment]
@jarrilla The item name seems to be missing from the data as well. Do I need to call something like `workOrders/packingQueue` or `workOrders/` and then filter for the item names? Or do we need to add this data to the endpoint?

**Comment by jbolles94** [comment]
@jarrilla What should the info button on the Due Date say?

**Comment by jarrilla** [comment]
> @jarrilla It looks like the endpoint `localhost:3000/shipments/queue` is missing the Due Date data for the shipping queue. Do we need an issue to add that data to the queue or am I missing a piece of it? 
> 

Looks like an issue is necessary. I seem to have overlooked this.

**Comment by jarrilla** [comment]
> @jarrilla The item name seems to be missing from the data as well. Do I need to call something like `workOrders/packingQueue` or `workOrders/` and then filter for the item names? Or do we need to add this data to the endpoint? 

I noticed this whole working on deep search. I'm almost done with that one, which is very similar. Can have them both done tomorrow.

**Comment by jarrilla** [comment]
> 

@jbolles94 We've removed due date from this page. It's no longer necessary. I will upload revised mock-up shortly.
