### ISSUE TITLE
Add "Select All" checkbox for Shipping Queue & Packing Queue

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#64]
Behavior should be:
- If all selectable rows are selected -> click should de-select all
- If at least one row is selected & more rows are selectable -> select the rest of selectable rows
- If no rows are selected, select all selectable rows using first row (top to bottom) as the filter

![image](https://user-images.githubusercontent.com/1864792/151852136-96638aaa-1794-4585-a611-372550c8b1d8.png)

**Comment by joshplumley** [comment]
@jarrilla I found some odd behavior that I dont think is intended, but I want to double check: 

On the shipping queue, when you select a row, that row moves to the top. I think you want it to stay in place and only move it to the top (sticky) when we search or sort, right?

If so, I'll most likely fix it here in this branch.

**Comment by jarrilla** [comment]
Hmm.. good catch.
I want to say that your proposal sounds right.
I hope there aren't too many edge cases to look for, though.

**Comment by joshplumley** [comment]
I dontt think there is. I have the packing queue working as outlined in this issue. I think when I added the sticky rows on sort, this bug got added. I didnt catch it till now.
