### ISSUE TITLE
Shipping History

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#8]
- [x] REPLACE "Order" with "Customer" cell values will be Customer Tag (e.g. ABC)
- [x] "Search" should be triggered by press of a "Search" button (#11 )
- [ ] ~Right clicking any line should bring up a context menu with [ View, Edit, PDF, Delete ]~
- [ ] ~View -> Page 16~
- [ ] ~Edit -> #9~
- [ ] ~PDF -> @jarrilla~
- [ ] ~Delete -> "Are you sure you want to delete this" (modal) double confirm -> DELETE `/shipments/{{ shipment _id }}`~

**Comment by joshplumley** [comment]
UPDATE TO SHIPMENTS HISTORY
- Removed "Date Due" from Queue
- (In History) Added "Order", "Part", "Search" to trigger the deep-search endpoint
- (In History) Moved "Filter" to the right.

Search should trigger endpoint POST "/shipments/search"
On Page load, we can just hit GET "/shipments"

![Screenshot from 2022-01-15 08-37-34](https://user-images.githubusercontent.com/8578990/149623676-fc80db19-1333-4b36-9617-6f893d9f76ef.png)

**Comment by joshplumley** [comment]
@jarrilla, do both the Order and Part need to be provided to perform a search? Or just one or the other?

**Comment by jarrilla** [comment]
One or both. The exact criteria `(!matchOrder || !matchPart)`

**Comment by jarrilla** [comment]
One more update:
As mentioned in #28, the following changes have been made to the table
Col1 (Customer) -> Shipment ID
Col2 (Shipment #) -> Tracking #

![image](https://user-images.githubusercontent.com/1864792/149837640-45619c33-12ff-4978-ba05-e1ede165c3d6.png)

**Comment by jarrilla** [comment]
Moved context menu requirements to new issue #32
