### ISSUE TITLE
Suggestion: When creating a packing slip

### ISSUE THREAD

**Issue by joshplumley** [conturo-prototyping/pack-ship-demo#81]
When you create a packing slip and edit the pack qty, you have to click off the cell first and then press "OK" (since the button is not enabled yet). @jarrilla Would you like it so that we can just press OK immediately, so that we are only one click away from submitting rather  than two?

**Comment by jarrilla** [comment]
Good idea! If that is possible, yes.

**Comment by jbolles94** [comment]
Closed by #88
