### ISSUE TITLE
Edit Shipment

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#9]
Individual line items of a packing slip are immutable from here. To edit that, a specific packing sleep would have to be edited.
Packing slips can be removed or added to a shipment, however.

- [x] Title -> "Edit Shipment / {{customer tag }} {{ shipment # }}"; e.g. "Edit Shipment / ABC-SH1"

- [x] Contents for each packing slip should be pulled from API (#12 )
- [x] Delete Action -> Remove the packing slip and all its parts from this shipment.
- [x] Clicking each packing slip line toggles its contents (view only)

**If `deliveryMethod == 'DROPOFF' | 'PICKUP'` make the following change:**
- [x] Bottom section is just "Customer Name:" label + text input (where default value is `customerName` from shipment data)

**If `deliveryMethod == 'CARRIER'` the following apply:**
- [ ] ~Career~ Carrier Service (typo)
- [ ] All delivery fields (service, speed, account, tracking, cost) are editable just as in the "Create Shipment" page
- [ ] OK Validation (same as "Create Shipment")
- [ ] OK -> PATCH `/shipments/{{ shipment _id }}`; body:
```
{
  manifest: [ ] // array of packing slip _ids
  trackingNumber?: String,
  cost?: number,
  carrier?: String,
  deliverySpeed?: String,
  customerAccount?: String
}
```

**Comment by joshplumley** [comment]
I think I can abstract this so that View and Edit are the same component

**Comment by joshplumley** [comment]
@jarrilla Re.  Delete Action -> Remove the packing slip and all its parts from this shipment.

After pressing the trash icon and then pressing confirm on the dialog to finally delete the packing slip, should DELETE packingslips/id be called AND DELETE shipments/id for all the shipment ids within the packing slip, or should the shipping object be maintained?

**Comment by jarrilla** [comment]
@joshplumley Good question. We should **avoid** using delete since there's a chance the user might change their mind and want to cancel pending changes, in which case delete won't be undone.

Let's stick to PATCH.

**Comment by joshplumley** [comment]
@jarrilla When we add a row to the edit shipment table, what should be populating that packing slip dropdown? All possible packing slips? Some subset?

**Comment by joshplumley** [comment]
@jarrilla Should there be another dropdown on this dialog to reflect the deliveryMethod ?

**Comment by joshplumley** [comment]
@jarrilla Would you like a delete confirmation when pressing the trash icon of the edit dialog next to each packing slip?

**Comment by joshplumley** [comment]
@jarrilla When we show the customer name to be edited on dropoff or pickup, should we be editing a customerName on the customer object? Does that still need added to the customer model?

**Comment by joshplumley** [comment]
> @jarrilla When we show the customer name to be edited on dropoff or pickup, should we be editing a customerName on the customer object? Does that still need added to the customer model?

Nevermind, I now see a `customerHandoffName` as part of the shipment

**Comment by jarrilla** [comment]
> 

All possible packing slips
I.e. shipping queue filtered to match customer

**Comment by jarrilla** [comment]
> @jarrilla When we add a row to the edit shipment table, what should be populating that packing slip dropdown? All possible packing slips? Some subset?

All possible packing slips
I.e. shipping queue filtered to match customer

**Comment by jarrilla** [comment]
> @jarrilla Would you like a delete confirmation when pressing the trash icon of the edit dialog next to each packing slip? (even though its a patch)

This seems like a good idea; yes.

**Comment by jarrilla** [comment]
> @jarrilla Should there be another dropdown on this dialog to reflect the deliveryMethod ?

Nah, it would be a pretty big mistake if this happened and some heads would roll. I don't anticipate this being an issue.

**Comment by jarrilla** [comment]
> @joshplumley Good question. We should **avoid** using delete since there's a chance the user might change their mind and want to cancel pending changes, in which case delete won't be undone.
> 
> Let's stick to PATCH.

@joshplumley 
I've thought about this a little more given your concern (https://github.com/conturo-prototyping/pack-ship-demo/issues/9#issuecomment-1019385806).

I think the PATCH route will need to accept an additional body attribute `deletedPackingSlips` so the shipping queue is properly updated. 

Related: #51

**Comment by joshplumley** [comment]
> > @joshplumley Good question. We should **avoid** using delete since there's a chance the user might change their mind and want to cancel pending changes, in which case delete won't be undone.
> > Let's stick to PATCH.
> 
> @joshplumley I've thought about this a little more given your concern ([#9 (comment)](https://github.com/conturo-prototyping/pack-ship-demo/issues/9#issuecomment-1019385806)).
> 
> I think the PATCH route will need to accept an additional body attribute `deletedPackingSlips` so the shipping queue is properly updated.
> 
> Related: #51

Rather than add another field to the PATH on the shipment endpoint, could we call the PATCH packingslip/id and remove the shipment when the user removes the packing slip for the edit shipment dialog (after they press confirm of course)

**Comment by joshplumley** [comment]
> +1
> 
> The benefit of doing it this way is that we only have to ping the server once, whereas otherwise we would queue multiple requests. The marginal cost of adding data to the payload is considerably lower than that of enqueuing multiple requests.

Yea I agree. My only concern/question was that now the PATCH endpoint has a `manifest` AND a `deletedPackingSlips`, so the question becomes which has priority. To avoid confusion I just removed the manifest param so now if you want to change the manifest we can simply use the two new params (deletedPackingSlips and newPackingSlips). If you want me to change that, just let me know.
