### ISSUE TITLE
Clean up tasks for Packing Slip

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-demo#90]
- [ ] Pack Qty cells should be very obviously editable (i.e. no need to double click; they should feel more like native inputs)
- [ ] When first opening modal, focus first row's Pack Qty input

**Comment by jarrilla** [comment]
@joshplumley Can we re-visit this. Through some end-user testing it was reported that having to do this double click is very annoying. Especially since a decent amount of our orders will have 15-20 line items and doing a double-click on every single one will be far too tedious.

I'm aware this would be R&D intensive.

**Comment by jarrilla** [comment]
@jbolles94 I have sent a license code for mui-x-pro to Josh. You should be good to keep going on this with that.

**Comment by zhull-jcs** [comment]
Hey @jarrilla Just checking in to see if you had a chance to review the PR associated with this issue.
